# Unmixing signals with ICA

Unmixing sound signals is an example of cocktail party problem you are going to use for getting hands-on experience with ICA. You have 5 mixed sound sources in **mixed** folder (go check them out). Your goal is to unmix them.

In [1]:
import scipy.io.wavfile
import numpy as np
from copy import deepcopy
%matplotlib inline

### Loading data from WAV files

Loading data from WAV files

In [2]:
dataset = []
for i in range(1,6):
    sample_rate, wav_data = scipy.io.wavfile.read('mixed/mix'+str(i)+'.wav')
    dataset.append(wav_data)

dataset = np.array(dataset).T
print(dataset.shape)
print(dataset[:10,:])

(53442, 5)
[[ 343 -546 -327 -275  612]
 [ 627 -840 -579 -124  890]
 [ 589 -725 -491 -115  989]
 [ 712 -887 -571  -24 1111]
 [ 589 -725 -491 -115  989]
 [ 268 -462 -146 -236  678]
 [ 107 -330   27 -296  522]
 [-214  -67  372 -416  211]
 [-214  -67  372 -416  211]
 [ 159 -206  -26 -233  445]]


Normalizing data

In [3]:
maxs = np.max(np.abs(dataset), axis=0).astype(np.int64)
data_normalized = 0.99 * dataset / maxs;
print(data_normalized[:10,:])
data_normalized.shape

[[ 0.01046796 -0.01666328 -0.00997965 -0.00839268  0.01867752]
 [ 0.0191353  -0.02563581 -0.0176704  -0.00378433  0.02716175]
 [ 0.01797558 -0.02212614 -0.01498474 -0.00350966  0.03018311]
 [ 0.0217294  -0.02707019 -0.01742625 -0.00073245  0.03390641]
 [ 0.01797558 -0.02212614 -0.01498474 -0.00350966  0.03018311]
 [ 0.00817904 -0.01409969 -0.00445575 -0.00720244  0.02069176]
 [ 0.00326551 -0.01007121  0.00082401 -0.00903357  0.01593082]
 [-0.00653103 -0.00204476  0.011353   -0.01269583  0.00643947]
 [-0.00653103 -0.00204476  0.011353   -0.01269583  0.00643947]
 [ 0.00485249 -0.00628688 -0.00079349 -0.00711089  0.01358087]]


(53442, 5)

### Implementing ICA

Initializing unmixing matrix $ W $.

In [4]:
W = np.identity(5)

Implement learning unmixing matrix $ W $ with ICA.

In [5]:
def sigmoid(X):
    return 1 / (1 + np.exp(-X))

In [6]:
# =============== TODO: Your code here ===============
# Implement learning unmixing matrix W with ICA. Do not forget to account for the dimensionality.
alpha = 0.1

def learn_optimal_W(W, alpha, epsilon=0.01):
    convergence = False
    iteration = 0
    loss_history = []

    while not convergence:
        previous_W = deepcopy(W)

        # gradient ascent
        for item in data_normalized:
            left_matrix = np.dot((1 - 2 * sigmoid(np.dot(W, item.T)[:,np.newaxis])), item[np.newaxis, :])
            W += alpha * (left_matrix + np.linalg.inv(W.T))

        # calc loss as norm of w - previous_W
        loss = np.linalg.norm(W - previous_W)    
        if loss_history and abs(loss - loss_history[-1]) < epsilon:
            convergence = True

        iteration += 1
        loss_history.append(loss)

        print("Iteration: {0:2d}    Loss: {1:.3f}".format(iteration, loss))

learn_optimal_W(W, alpha)
# ====================================================

Iteration:  1    Loss: 99.490
Iteration:  2    Loss: 15.333
Iteration:  3    Loss: 8.542
Iteration:  4    Loss: 5.434
Iteration:  5    Loss: 4.147
Iteration:  6    Loss: 3.584
Iteration:  7    Loss: 3.263
Iteration:  8    Loss: 3.013
Iteration:  9    Loss: 2.774
Iteration: 10    Loss: 2.532
Iteration: 11    Loss: 2.294
Iteration: 12    Loss: 2.074
Iteration: 13    Loss: 1.886
Iteration: 14    Loss: 1.738
Iteration: 15    Loss: 1.633
Iteration: 16    Loss: 1.573
Iteration: 17    Loss: 1.556
Iteration: 18    Loss: 1.584
Iteration: 19    Loss: 1.659
Iteration: 20    Loss: 1.786
Iteration: 21    Loss: 1.978
Iteration: 22    Loss: 2.262
Iteration: 23    Loss: 2.684
Iteration: 24    Loss: 3.340
Iteration: 25    Loss: 4.402
Iteration: 26    Loss: 5.913
Iteration: 27    Loss: 6.633
Iteration: 28    Loss: 7.094
Iteration: 29    Loss: 7.605
Iteration: 30    Loss: 7.464
Iteration: 31    Loss: 6.872
Iteration: 32    Loss: 5.970
Iteration: 33    Loss: 4.943
Iteration: 34    Loss: 3.981
Iteration: 3

KeyboardInterrupt: 

Obviously this learning rate (alpha=0.1) is too large. Let's try smaller

In [7]:
alpha = 0.05
W = np.identity(5)

learn_optimal_W(W, alpha)

Iteration:  1    Loss: 82.462
Iteration:  2    Loss: 14.983
Iteration:  3    Loss: 8.963
Iteration:  4    Loss: 5.999
Iteration:  5    Loss: 4.379
Iteration:  6    Loss: 3.616
Iteration:  7    Loss: 3.214
Iteration:  8    Loss: 2.877
Iteration:  9    Loss: 2.525
Iteration: 10    Loss: 2.181
Iteration: 11    Loss: 1.873
Iteration: 12    Loss: 1.609
Iteration: 13    Loss: 1.387
Iteration: 14    Loss: 1.201
Iteration: 15    Loss: 1.047
Iteration: 16    Loss: 0.919
Iteration: 17    Loss: 0.812
Iteration: 18    Loss: 0.723
Iteration: 19    Loss: 0.648
Iteration: 20    Loss: 0.584
Iteration: 21    Loss: 0.530
Iteration: 22    Loss: 0.485
Iteration: 23    Loss: 0.445
Iteration: 24    Loss: 0.411
Iteration: 25    Loss: 0.382
Iteration: 26    Loss: 0.357
Iteration: 27    Loss: 0.334
Iteration: 28    Loss: 0.315
Iteration: 29    Loss: 0.298
Iteration: 30    Loss: 0.283
Iteration: 31    Loss: 0.269
Iteration: 32    Loss: 0.258
Iteration: 33    Loss: 0.247
Iteration: 34    Loss: 0.238


Try smaller alpha.

In [8]:
alpha = 0.001
W = np.identity(5)

learn_optimal_W(W, alpha)

Iteration:  1    Loss: 16.971
Iteration:  2    Loss: 6.741
Iteration:  3    Loss: 4.891
Iteration:  4    Loss: 3.916
Iteration:  5    Loss: 3.290
Iteration:  6    Loss: 2.845
Iteration:  7    Loss: 2.509
Iteration:  8    Loss: 2.246
Iteration:  9    Loss: 2.033
Iteration: 10    Loss: 1.856
Iteration: 11    Loss: 1.708
Iteration: 12    Loss: 1.582
Iteration: 13    Loss: 1.472
Iteration: 14    Loss: 1.377
Iteration: 15    Loss: 1.294
Iteration: 16    Loss: 1.220
Iteration: 17    Loss: 1.154
Iteration: 18    Loss: 1.095
Iteration: 19    Loss: 1.042
Iteration: 20    Loss: 0.995
Iteration: 21    Loss: 0.951
Iteration: 22    Loss: 0.912
Iteration: 23    Loss: 0.877
Iteration: 24    Loss: 0.844
Iteration: 25    Loss: 0.814
Iteration: 26    Loss: 0.787
Iteration: 27    Loss: 0.762
Iteration: 28    Loss: 0.739
Iteration: 29    Loss: 0.717
Iteration: 30    Loss: 0.697
Iteration: 31    Loss: 0.679
Iteration: 32    Loss: 0.661
Iteration: 33    Loss: 0.645
Iteration: 34    Loss: 0.629
Iteration: 35

Then larger and smaller epsilon.

In [9]:
alpha = 0.01
W = np.identity(5)

learn_optimal_W(W, alpha, epsilon=0.001)

Iteration:  1    Loss: 47.959
Iteration:  2    Loss: 13.114
Iteration:  3    Loss: 8.086
Iteration:  4    Loss: 5.951
Iteration:  5    Loss: 4.816
Iteration:  6    Loss: 4.078
Iteration:  7    Loss: 3.505
Iteration:  8    Loss: 3.028
Iteration:  9    Loss: 2.623
Iteration: 10    Loss: 2.278
Iteration: 11    Loss: 1.981
Iteration: 12    Loss: 1.727
Iteration: 13    Loss: 1.509
Iteration: 14    Loss: 1.323
Iteration: 15    Loss: 1.165
Iteration: 16    Loss: 1.031
Iteration: 17    Loss: 0.917
Iteration: 18    Loss: 0.820
Iteration: 19    Loss: 0.738
Iteration: 20    Loss: 0.667
Iteration: 21    Loss: 0.607
Iteration: 22    Loss: 0.556
Iteration: 23    Loss: 0.511
Iteration: 24    Loss: 0.473
Iteration: 25    Loss: 0.440
Iteration: 26    Loss: 0.410
Iteration: 27    Loss: 0.384
Iteration: 28    Loss: 0.361
Iteration: 29    Loss: 0.341
Iteration: 30    Loss: 0.322
Iteration: 31    Loss: 0.305
Iteration: 32    Loss: 0.290
Iteration: 33    Loss: 0.275
Iteration: 34    Loss: 0.262
Iteration: 3

### Unmixing sounds

Use learned matrix $ W $ to unmix the sounds into separate data sources. Make sure you represent the resulting unmixing matrix in a way so that each row is a separate track (i.e. the matrix should have 5 rows).

In [10]:
# =============== TODO: Your code here ===============
# Use learned matrix W to unmix the sounds into separate data sources.

unmixed = W.dot(data_normalized.T)

# ====================================================

Saving unmixed sounds. Please note that some players may not support the resulting WAV format. If that is the case, you can use Winamp to play the unmixed sounds.

In [11]:
maxs = np.max(np.abs(unmixed), axis=1)[:,  np.newaxis]
unmixed_normalized = 0.99 * unmixed / maxs;

for i in range(unmixed_normalized.shape[0]):
    track = unmixed_normalized[i,:]
    scipy.io.wavfile.write('unmixed/unmixed'+str(i)+'.wav', sample_rate, track)